### ISSUE TITLE
Error when running `pip install -r requirements.txt`

### ISSUE THREAD

**Issue by TroyCoombs** [Aiven-Open/metadata-parser#45]
# What can we help you with?

When I run `pip install -r requirements.txt` I get the below,

```
ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build psycopg2
Installing collected packages: psycopg2, dash, cryptography, configparser, colour
    Running setup.py install for psycopg2 ... error
```

Not sure what I'm missing.

# Where would you expect to find this information?

**Comment by encima** [comment]
This is [likely](https://pypi.org/project/psycopg2-binary/) because you do not have `postgresql` installed locally. Can you try installing `psycopg2-binary`?
